FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["PortfolioAPI.csproj", "./"]
RUN dotnet restore "PortfolioAPI.csproj"
COPY . .
RUN dotnet build "PortfolioAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PortfolioAPI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://+:5000
CMD ["dotnet", "PortfolioAPI.dll"]
